# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-24 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180722_1811'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ad',
        ),
        migrations.DeleteModel(
            name='Links',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='url',
        ),
        migrations.AlterField(
            model_name='article',
            name='click_count',
            field=models.PositiveIntegerField(default=0, verbose_name='\u70b9\u51fb\u6b21\u6570'),
        ),
    ]
